import * as fs from 'fs'
import reREADME from '../../lib'

describe('When using reREADME', () => {
  it('should generate latest README without badges', async () => {
    const expectedREADMEcontents = `# rereadme\nan exploration on creating a readme file generator\n\n#\n<sub><sup>this README.md is generated by this package!<sup></sub>`
    
    const contents = {
      header: `# rereadme
an exploration on creating a readme file generator`,
      footer: '<sub><sup>this README.md is generated by this package!<sup></sub>'
    }

    await reREADME({
      outputPath: './README.md',
      contents,
    })

    fs.readFile('./README.md', (err, data) => {
      if (err) throw err
      expect(data.toString('utf-8')).toEqual(expectedREADMEcontents)
    })
  })

  it('should generate latest README with badges', async () => {
    const expectedREADMEcontents = `# rereadme\nan exploration on creating a readme file generator\n\n## Package Status\n### \`dependencies\`\n[![](https://img.shields.io/static/v1?label=npm-check&message=^5.9.2%20→%205.9.2&color=green)](https://github.com/dylang/npm-check)\n### \`devDependencies\`\n[![](https://img.shields.io/static/v1?label=@babel/core&message=^7.16.5%20→%207.16.5&color=green)](https://babel.dev/docs/en/next/babel-core)[![](https://img.shields.io/static/v1?label=@babel/preset-env&message=^7.16.5%20→%207.16.5&color=green)](https://babel.dev/docs/en/next/babel-preset-env)[![](https://img.shields.io/static/v1?label=@types/jest&message=^27.0.3%20→%2027.0.3&color=green)](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/jest)[![](https://img.shields.io/static/v1?label=@types/node&message=^17.0.0%20→%2017.0.0&color=green)](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/node)[![](https://img.shields.io/static/v1?label=babel-jest&message=^27.4.5%20→%2027.4.5&color=green)](https://github.com/facebook/jest#readme)[![](https://img.shields.io/static/v1?label=jest&message=^27.4.5%20→%2027.4.5&color=green)](https://jestjs.io/)[![](https://img.shields.io/static/v1?label=tslib&message=^2.3.1%20→%202.3.1&color=green)](https://www.typescriptlang.org/)[![](https://img.shields.io/static/v1?label=typescript&message=^4.5.4%20→%204.5.4&color=green)](https://www.typescriptlang.org/)\n\n#\n<sub><sup>this README.md is generated by this package!<sup></sub>`
    
    const contents = {
      header: `# rereadme
an exploration on creating a readme file generator`,
      footer: '<sub><sup>this README.md is generated by this package!<sup></sub>'
    }

    await reREADME({
      outputPath: './README.md',
      contents,
      badges: true,
    })

    fs.readFile('./README.md', (err, data) => {
      if (err) throw err
      expect(data.toString('utf-8')).toEqual(expectedREADMEcontents)
    })
  })

  it.todo('should order badges by (1st: other bump, 2nd: latest, 3rd: patch, 4th: minor, 5th: major)')
})
